# Generated by Django 5.2.2 on 2025-06-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificates_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
