# Generated by Django 5.2.2 on 2025-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_certificates_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='certificates',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_thumbnails/'),
        ),
    ]
