name: Keep Render Sites Awake

on:
  schedule:
    - cron: '*/14 * * * *'  # every 14 minutes
  workflow_dispatch:

jobs:
  ping-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Curl portfolio site
        run: curl -s https://deniskuriandeepu-portfolio.onrender.com > /dev/null

      - name: Curl toolshare site
        run: curl -s https://toolshare-7lhe.onrender.com > /dev/null

